# Usa un'immagine Node.js ufficiale come base
FROM node:14

# Crea la directory dell'applicazione
WORKDIR /usr/src/app

# Copia package.json e package-lock.json
COPY package*.json ./

# Installa le dipendenze
RUN npm install

# Se stai buildando per la produzione
# RUN npm ci --only=production

# Copia i file sorgente
COPY . .

# Esponi la porta su cui l'app sarà in ascolto
EXPOSE 1337

# Comando per avviare l'applicazione
CMD [ "npm", "start" ]
